### ISSUE TITLE
Arules package not working after dendextend has been loaded

### ISSUE THREAD

**Issue by theclue** [talgalili/dendextend#17] opened 2015-11-10 15:38 UTC
I'm not sure if this bug is related to dendextend rather than arules itself. It looks like there is a masking glitch here or there...

Anyway, here's how to reproduce the defect:

```r
require(arules)
a_matrix <- matrix(c(
  1,1,1,0,0,
  1,1,0,0,0,
  1,1,0,1,0,
  0,0,1,0,1,
  1,1,0,1,1
), ncol = 5)

## set dim names
dimnames(a_matrix) <- list(c("a","b","c","d","e"),
                           paste("Tr",c(1:5), sep = ""))

a_matrix

## this works
trans1 <- as(a_matrix, "transactions")

## this mess up the whole thing
require(dendextend)
trans2 <- as(a_matrix, "transactions")
```

hope this help!

regards,
gabriele

**Comment by talgalili** [comment] 2015-11-10 15:41
Hi gabriele,
I can't reproduce any problem.

I remember this was a problem once that I fixed in later versions of dendextend.
What is your sessionInfo() (or what version of dendextend are you using) ?

**Comment by theclue** [comment] 2015-11-10 15:51
Hi,

here's my sessionInfo.
```r
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dendextend_1.1.0    bggAnalysis_0.0.1   RColorBrewer_1.1-2  dummies_1.5.6       cluster_2.0.3       arulesViz_1.0-2     ggplot2_1.0.1       dplyr_0.4.2        
 [9] arules_1.1-9        Matrix_1.2-2        RevoUtilsMath_3.2.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0           plyr_1.8.3            bitops_1.0-6          iterators_1.0.7       tools_3.2.2           digest_0.6.8          gtable_0.1.2         
 [8] lattice_0.20-33       foreach_1.4.2         DBI_0.3.1             registry_0.3          parallel_3.2.2        seriation_1.1-2       proto_0.3-10         
[15] TSP_1.1-2             stringr_1.0.0         gtools_3.5.0          caTools_1.17.1        lmtest_0.9-34         vcd_1.4-1             scatterplot3d_0.3-36 
[22] data.table_1.9.4      R6_2.1.1              gdata_2.17.0          whisker_0.3-2         reshape2_1.4.1        magrittr_1.5          scales_0.3.0         
[29] gplots_2.17.0         codetools_0.2-14      gclus_1.3.1           MASS_7.3-43           assertthat_0.1        splitstackshape_1.4.2 colorspace_1.2-6     
[36] labeling_0.3          KernSmooth_2.23-15    stringi_0.5-5         lazyeval_0.1.10       munsell_0.4.2         chron_2.3-47          zoo_1.7-12
```

I'm using RevolutionR now...perhaps the version on MRAN of dendextend is older than the one on CRAN?

**Comment by talgalili** [comment] 2015-11-10 15:53
You should upgrade to dendextend 1.1.2.
As you can see here:
https://cran.r-project.org/web/packages/dendextend/NEWS

dendextend 1.1.2 (2015-10-30)
----------------------------------------
###UPDATED FUNCTIONS:
   * Removed functions labels.matrix and labels<-.matrix, in order to avoid conflicts with arules (and since these functions are not really used in other parts of the package) - reported by Maja Alicja.

**Closed by talgalili** 2015-11-10 15:53 UTC

**Comment by theclue** [comment] 2015-11-10 15:56
I confirm that installing the most updated version from github solves the problem

(stupid MRAN...)

**Comment by talgalili** [comment] 2015-11-10 15:56
Great :+1:

**Comment by talgalili** [comment] 2015-11-10 15:57
BTW, if you use dendextend for something which is online, please let me know and I'll gladly mention it on the package so others would know about it.

**Comment by theclue** [comment] 2015-11-10 16:31
I'm using here actually: https://github.com/theclue/bgg-analysis/tree/exploratory-analysis

still under heavy development, though :)
